### ISSUE TITLE
210822 TODO

### ISSUE THREAD

**Issue by recordbuffer** [semo41105/custom-erProject#22]
- [x] 상품 등록 (사진 업로드)
- [ ]  상품 제작 (사진 업로드) > 보류 다음주로
  - [x] 상품 선택 > 제작 페이지 이동
  - [x] 제작 페이지 레이아웃 설정
  - [ ] 사진 업로드 기능 구현
  - [x] #23
- [ ]  주문 기능
  - [ ] #24
  - [x] #26
  - [ ] #28 
  - [ ] #27
